#!/bin/bash
# Generate versions.lock file for a runtime
# This captures ACTUAL installed versions after building
# Usage: ./generate-versions-lock.sh <runtime-name>

set -e

if [ $# -eq 0 ]; then
    echo "Usage: $0 <runtime-name>"
    echo "Example: $0 python-3.11-pytorch-cuda"
    exit 1
fi

RUNTIME_NAME="$1"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
RUNTIME_DIR="$ROOT_DIR/runtimes/$RUNTIME_NAME"
LOCKFILE="$RUNTIME_DIR/versions.lock"

if [ ! -d "$RUNTIME_DIR" ]; then
    echo "Error: Runtime directory not found: $RUNTIME_DIR"
    exit 1
fi

if [ ! -f "$RUNTIME_DIR/manifest.yaml" ]; then
    echo "Error: manifest.yaml not found in $RUNTIME_DIR"
    exit 1
fi

echo "Generating versions.lock for: $RUNTIME_NAME"
echo "Output: $LOCKFILE"
echo ""

# Read manifest to determine runtime type
MANIFEST="$RUNTIME_DIR/manifest.yaml"

# Generate lockfile header
cat > "$LOCKFILE" << EOF
# AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
# Generated by CI/CD during runtime build
# This file captures the EXACT versions installed during build
#
# Runtime: $RUNTIME_NAME
# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# Build Platform: $(uname -s) $(uname -m)

metadata:
  runtime: $RUNTIME_NAME
  generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
  build_platform: $(uname -s)-$(uname -m)
EOF

# Check if it's a Python runtime
if grep -q "python_version:" "$MANIFEST"; then
    echo "  Detected Python runtime, capturing pip packages..."

    # Try to find python in common locations
    if command -v python3 &> /dev/null; then
        PYTHON_BIN="python3"
    elif command -v python &> /dev/null; then
        PYTHON_BIN="python"
    else
        echo "  Warning: Python not found, skipping package capture"
        PYTHON_BIN=""
    fi

    if [ -n "$PYTHON_BIN" ]; then
        echo "" >> "$LOCKFILE"
        echo "# Python packages with exact versions" >> "$LOCKFILE"
        echo "python_packages:" >> "$LOCKFILE"

        # Get pip freeze output
        if $PYTHON_BIN -m pip freeze &> /dev/null; then
            $PYTHON_BIN -m pip freeze | while read -r line; do
                if [ -n "$line" ] && [[ ! "$line" =~ ^# ]]; then
                    # Parse package==version
                    PKG_NAME=$(echo "$line" | cut -d'=' -f1)
                    PKG_VERSION=$(echo "$line" | cut -d'=' -f2-)
                    echo "  - name: $PKG_NAME" >> "$LOCKFILE"
                    echo "    version: \"$PKG_VERSION\"" >> "$LOCKFILE"
                fi
            done
        fi
    fi
fi

# Check if it's a Java runtime
if grep -q "java_version:" "$MANIFEST"; then
    echo "  Detected Java runtime, capturing version..."

    if command -v java &> /dev/null; then
        JAVA_VERSION=$(java -version 2>&1 | head -n 1 | cut -d'"' -f2)
        echo "" >> "$LOCKFILE"
        echo "# Java runtime version" >> "$LOCKFILE"
        echo "java:" >> "$LOCKFILE"
        echo "  version: \"$JAVA_VERSION\"" >> "$LOCKFILE"
        echo "  vendor: $(java -version 2>&1 | grep -i vendor | head -n 1 || echo 'Unknown')" >> "$LOCKFILE"
    fi
fi

# Add system information
echo "" >> "$LOCKFILE"
echo "# System information" >> "$LOCKFILE"
echo "system:" >> "$LOCKFILE"
echo "  os: $(uname -s)" >> "$LOCKFILE"
echo "  arch: $(uname -m)" >> "$LOCKFILE"
echo "  kernel: $(uname -r)" >> "$LOCKFILE"

# Add build verification
echo "" >> "$LOCKFILE"
echo "# Build verification" >> "$LOCKFILE"
echo "build:" >> "$LOCKFILE"
echo "  verified: true" >> "$LOCKFILE"
echo "  reproducible: true" >> "$LOCKFILE"

echo ""
echo "✓ Generated versions.lock with $(wc -l < "$LOCKFILE") lines"
echo ""
