# Joblet Runtime Registry Configuration
# For use with Joblet - https://github.com/joblet/joblet
# Location: ~/.rnx/config.yaml or /etc/joblet/config.yaml
#
# Runtime Notation (npm-style):
#   runtime-name@version
#
# Examples:
#   python-3.11-pytorch-cuda@1.0.0   (specific version - recommended for production)
#   python-3.11-pytorch-cuda@latest  (latest stable version)
#   python-3.11-pytorch-cuda         (omitting @version defaults to @latest)
#
# Note: For reproducibility, always use specific versions in production!

runtimes:
  # Registry sources (multiple registries supported)
  registries:
    # Official Joblet runtime registry
    - name: official
      url: https://github.com/joblet/joblet-runtimes
      enabled: true
      verify_checksums: true

    # Optional: Company private registry
    # - name: company-private
    #   url: https://github.com/mycompany/joblet-runtimes
    #   enabled: true
    #   verify_checksums: true
    #   auth:
    #     type: token
    #     token_env: GITHUB_TOKEN

    # Optional: Local development
    # - name: local-dev
    #   url: file:///home/user/joblet-runtimes
    #   enabled: true
    #   verify_checksums: false

  # Cache configuration
  cache_dir: /opt/joblet/runtime-cache
  cache_max_size_gb: 50
  cache_retention_days: 30
  cache_enabled: true

  # Download settings
  download:
    timeout_seconds: 300
    retry_attempts: 3
    parallel_downloads: 4
    verify_checksums: true
    verify_signatures: false  # GPG signature verification (future)

  # Installation settings
  install:
    base_dir: /opt/joblet/runtimes
    cleanup_on_failure: true
    backup_existing: true
    verify_after_install: true

  # Version resolution
  version_resolution:
    allow_pre_release: false
    prefer_latest_stable: true
    auto_update: false  # Don't auto-update installed runtimes

  # Default runtime (optional, use @ for specific version)
  default_runtime: python-3.11@latest

  # Runtime aliases (use @ for versions)
  aliases:
    python: python-3.11@latest
    pytorch: python-3.11-pytorch-cuda@latest
    ml: python-3.11-ml@latest

# Job defaults
jobs:
  # Default resources if not specified
  defaults:
    runtime: python-3.11@latest
    cpu_cores: 2
    memory_mb: 4096
    timeout_minutes: 60

# Remote hosts configuration
hosts:
  # Default host for job execution
  default: 192.168.1.161

  # Host-specific configurations
  hosts:
    - name: gpu-server
      address: 192.168.1.161
      user: jay
      ssh_key: ~/.ssh/id_rsa
      runtimes_dir: /opt/joblet/runtimes
      capabilities:
        gpu: true
        gpu_count: 2
        gpu_memory_gb: 24

    - name: cpu-cluster
      address: 192.168.1.162
      user: jay
      ssh_key: ~/.ssh/id_rsa
      runtimes_dir: /opt/joblet/runtimes
      capabilities:
        gpu: false
        cpu_cores: 32
        memory_gb: 128

# Logging configuration
logging:
  level: info  # debug, info, warn, error
  format: json  # json or text
  output: /var/log/joblet/rnx.log
  rotation:
    max_size_mb: 100
    max_age_days: 7
    max_backups: 5

# Metrics and monitoring
metrics:
  enabled: true
  prometheus_port: 9090
  collect_runtime_metrics: true

# Security settings
security:
  # Allow only specific registries
  allowed_registries:
    - official
    - company-private
    - local-dev

  # Require checksum verification
  require_checksum_verification: true

  # Sandbox settings
  sandbox:
    enabled: true
    network_isolation: true
    filesystem_isolation: true

# Experimental features
experimental:
  runtime_layers: false  # Runtime inheritance/layers
  dependency_resolution: false  # Auto-resolve runtime dependencies
  parallel_installs: false  # Install multiple runtimes in parallel
